"""IQ file demodulator. Recovers bits from a .cf32 or .sigmf-data file
generated by iqgen (or compatible). Knows about all 10 modulations, all 5
pulse-shaping filters, and multi-frequency (concurrent or hopping).

This is a noise-free matched receiver — it knows the parameters (either
from SigMF metadata or supplied manually) and demodulates accordingly. It
is NOT a blind receiver; there's no carrier/timing recovery.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import numpy as np

from .config import BITS_PER_SYMBOL, VALID_FILTERS
from .filters import PulseShaper

log = logging.getLogger(__name__)


@dataclass
class ReceiveParams:
    """Everything the demodulator needs. Populated either from SigMF
    metadata or directly by the caller."""

    modulation: str
    sample_rate: float
    bitrate: float
    filter_type: str = "none"
    span_symbols: int = 10
    roll_off: float = 0.35
    bt_product: float = 0.35
    gray_coding: bool = True
    initial_phase: float = 0.0

    # multi-freq (defaults match generator: single carrier at offset 0)
    channel_mode: str = "concurrent"
    channel_offsets_hz: list = field(default_factory=lambda: [0.0])
    hop_duration_sec: Optional[float] = None

    @property
    def bits_per_symbol(self) -> int:
        return BITS_PER_SYMBOL[self.modulation]

    @property
    def symbol_rate(self) -> float:
        return self.bitrate / self.bits_per_symbol

    @property
    def samples_per_symbol(self) -> int:
        return int(round(self.sample_rate / self.symbol_rate))


# =============================================================================
# I/O
# =============================================================================

def load_iq(path) -> np.ndarray:
    """Read a .cf32 / .sigmf-data file as complex64."""
    p = Path(path)
    return np.fromfile(p, dtype=np.complex64)


def params_from_sigmf_meta(meta_path) -> ReceiveParams:
    """Build ReceiveParams from a .sigmf-meta JSON file written by iqgen.

    Reads the iqgen:* extension keys placed by SigMFWriter; if those are
    missing (file not from iqgen), raises with a hint to supply parameters
    manually instead.
    """
    p = Path(meta_path)
    meta = json.loads(p.read_text())
    g = meta.get("global", {})
    anns = meta.get("annotations") or []
    if not anns:
        raise ValueError(f"{p}: SigMF file has no annotations to read")
    a0 = anns[0]

    required = ("iqgen:modulation", "iqgen:bitrate")
    missing = [k for k in required if k not in a0]
    if missing:
        raise ValueError(
            f"{p}: missing iqgen extension keys {missing} in first annotation. "
            f"This file probably wasn't produced by iqgen — supply parameters "
            f"manually (modulation, bitrate, etc.)."
        )

    # Channels: rebuild offset list from per-carrier annotations (concurrent)
    # or use the global hop duration + ordered annotations (hopping).
    mode = g.get("iqgen:channel_mode", "concurrent")
    if mode == "hopping":
        # Preserve order from the annotation list (one per hop, round-robin
        # through the original offsets — distinct values give us the set).
        seen, offsets = set(), []
        for a in anns:
            f = float(a.get("iqgen:offset_hz", 0.0))
            if f not in seen:
                seen.add(f)
                offsets.append(f)
    else:
        offsets = [float(a.get("iqgen:offset_hz", 0.0)) for a in anns]
        if not offsets:
            offsets = [0.0]

    return ReceiveParams(
        modulation=a0["iqgen:modulation"],
        sample_rate=float(g["core:sample_rate"]),
        bitrate=float(a0["iqgen:bitrate"]),
        filter_type=a0.get("iqgen:pulse_shaping", "none"),
        span_symbols=10,  # not recorded; default — only affects matched filter
        roll_off=float(a0.get("iqgen:roll_off", 0.35)),
        bt_product=float(a0.get("iqgen:bt_product", 0.35)),
        gray_coding=bool(a0.get("iqgen:gray_coding", True)),
        channel_mode=mode,
        channel_offsets_hz=offsets,
        hop_duration_sec=float(g["iqgen:hop_duration_sec"])
            if "iqgen:hop_duration_sec" in g else None,
    )


def detect_format(path) -> str:
    """Return 'sigmf-meta', 'sigmf-data', or 'cf32' based on the extension."""
    p = Path(path)
    if p.suffix == ".sigmf-meta":
        return "sigmf-meta"
    if p.suffix == ".sigmf-data":
        return "sigmf-data"
    return "cf32"


def find_sigmf_data_for_meta(meta_path) -> Path:
    p = Path(meta_path)
    data = p.with_suffix(".sigmf-data")
    if not data.exists():
        raise FileNotFoundError(f"Missing matching .sigmf-data for {p}")
    return data


# =============================================================================
# Demodulation
# =============================================================================

def demodulate(iq: np.ndarray, params: ReceiveParams) -> np.ndarray:
    """Recover the transmitted bit stream. Returns a uint8 array of 0/1.

    Pipeline (inverse of generator):
      1. Multi-frequency: mix the selected carrier down to baseband. For
         concurrent mode the first offset is used (all carriers share the
         same baseband so any one works). For hopping mode each hop window
         is mixed by its own offset and concatenated.
      2. Matched filter for RRC only — for other filters the TX output
         is already at zero (or near-zero) ISI at symbol centers.
      3. Sample at symbol centers (post-convolution centering is taken
         care of by `mode='same'` in the generator).
      4. Demap symbols → bits.
    """
    if iq.size == 0:
        return np.zeros(0, dtype=np.uint8)

    iq = _downconvert(iq, params)

    if params.filter_type == "root_raised_cosine":
        # Cascade with another RRC at RX → full RC, zero-ISI at symbol centers.
        shaper = PulseShaper(
            params.filter_type, params.span_symbols,
            params.samples_per_symbol, params.roll_off, params.bt_product,
        )
        iq = shaper.apply(iq).astype(np.complex64)

    sps = params.samples_per_symbol
    if sps < 1:
        raise ValueError(f"samples_per_symbol={sps} < 1; check sample_rate/bitrate")

    if params.modulation == "oqpsk":
        symbols = _sample_oqpsk(iq, sps, params.filter_type)
    else:
        symbols = _sample_single(iq, sps, params.filter_type)

    return _demap(symbols, params)


def _downconvert(iq: np.ndarray, params: ReceiveParams) -> np.ndarray:
    """Mix the selected carrier(s) down to baseband. Returns a single
    complex64 stream ready for matched filter / sampling."""
    offsets = params.channel_offsets_hz or [0.0]
    fs = params.sample_rate

    if params.channel_mode == "hopping" and len(offsets) > 1:
        # Mix each hop window by its own -offset.
        spc = max(1, int(round((params.hop_duration_sec or 0.0) * fs)))
        out = iq.copy()
        for hop_idx, start in enumerate(range(0, iq.size, spc)):
            end = min(start + spc, iq.size)
            f = offsets[hop_idx % len(offsets)]
            if f == 0.0:
                continue
            t = np.arange(start, end, dtype=np.float64) / fs
            lo = np.exp(-2j * np.pi * f * t).astype(np.complex64)
            out[start:end] = (iq[start:end] * lo).astype(np.complex64)
        return out

    # Concurrent: pick the first carrier (all carry the same bits).
    f = offsets[0]
    if f == 0.0:
        return iq
    t = np.arange(iq.size, dtype=np.float64) / fs
    lo = np.exp(-2j * np.pi * f * t).astype(np.complex64)
    return (iq * lo).astype(np.complex64)


def _sample_single(iq: np.ndarray, sps: int, filter_type: str) -> np.ndarray:
    """Sample at symbol centers for non-OQPSK modulations."""
    if filter_type == "none":
        # Sample-and-hold: symbol n covers [n*sps, (n+1)*sps). Pick the middle.
        offset = sps // 2
    else:
        # generator applies the filter with mode='same', so symbol n is
        # centered at sample n*sps in the output.
        offset = 0
    if offset >= iq.size:
        return np.zeros(0, dtype=np.complex64)
    return iq[offset::sps].astype(np.complex64)


def _sample_oqpsk(iq: np.ndarray, sps: int, filter_type: str) -> np.ndarray:
    """OQPSK: I and Q peaks are offset by sps/2. Sample them separately
    and recombine into complex symbols."""
    half = sps // 2
    if filter_type == "none":
        # I hold window starts at n*sps; sample mid-window at sps/4.
        # Q hold window starts at n*sps + sps/2; sample mid-window at sps/2 + sps/4.
        i_off = sps // 4
        q_off = sps // 2 + sps // 4
    else:
        # Post-convolution (mode='same'): I peaks at n*sps, Q at n*sps + sps/2.
        i_off, q_off = 0, half
    if i_off >= iq.size or q_off >= iq.size:
        return np.zeros(0, dtype=np.complex64)
    i_s = iq.real[i_off::sps]
    q_s = iq.imag[q_off::sps]
    n = min(i_s.size, q_s.size)
    return (i_s[:n] + 1j * q_s[:n]).astype(np.complex64)


# =============================================================================
# Demappers (inverse of iqgen.mappers)
# =============================================================================

def _gray_to_binary_lut(k_bits: int) -> np.ndarray:
    n = 1 << k_bits
    lut = np.zeros(n, dtype=np.int64)
    for i in range(n):
        lut[i ^ (i >> 1)] = i
    return lut


def _indices_to_bits(idx: np.ndarray, bits_per_symbol: int) -> np.ndarray:
    """Inverse of mappers.bits_to_indices (MSB-first packing)."""
    if idx.size == 0:
        return np.zeros(0, dtype=np.uint8)
    out = np.zeros(idx.size * bits_per_symbol, dtype=np.uint8)
    for b in range(bits_per_symbol):
        # bit (bits_per_symbol - 1 - b) of each index sits at position b within the symbol
        shift = bits_per_symbol - 1 - b
        out[b::bits_per_symbol] = ((idx >> shift) & 1).astype(np.uint8)
    return out


def _angle_to_index(symbols: np.ndarray, m_points: int) -> np.ndarray:
    """Snap each symbol to the nearest of `m_points` equally-spaced PSK
    angles starting at 0. Returns indices 0..m_points-1."""
    if symbols.size == 0:
        return np.zeros(0, dtype=np.int64)
    angles = np.angle(symbols)                # (-π, π]
    angles = np.mod(angles, 2 * np.pi)        # [0, 2π)
    step = 2 * np.pi / m_points
    return (np.round(angles / step).astype(np.int64) % m_points)


def _demap(symbols: np.ndarray, params: ReceiveParams) -> np.ndarray:
    mod = params.modulation
    if mod == "bpsk":
        return _demap_bpsk(symbols)
    if mod == "pi2_bpsk":
        n = np.arange(symbols.size)
        de_rot = symbols * np.exp(-1j * (np.pi / 2) * n)
        return _demap_bpsk(de_rot)
    if mod == "dbpsk":
        return _demap_differential(symbols, base_mod="bpsk",
                                     initial_phase=params.initial_phase,
                                     gray_coding=params.gray_coding)
    if mod == "qpsk":
        return _demap_qpsk(symbols, params.gray_coding)
    if mod == "dqpsk":
        return _demap_differential(symbols, base_mod="qpsk",
                                     initial_phase=params.initial_phase,
                                     gray_coding=params.gray_coding)
    if mod == "pi4_qpsk":
        return _demap_pi4_qpsk(symbols, params.initial_phase)
    if mod == "oqpsk":
        return _demap_qpsk(symbols, params.gray_coding)
    if mod == "8psk":
        return _demap_8psk(symbols, params.gray_coding)
    if mod == "d8psk":
        return _demap_differential(symbols, base_mod="8psk",
                                     initial_phase=params.initial_phase,
                                     gray_coding=params.gray_coding)
    if mod == "pi4_8psk":
        n = np.arange(symbols.size)
        de_rot = symbols * np.exp(-1j * (np.pi / 8) * (n % 2))
        return _demap_8psk(de_rot, params.gray_coding)
    raise ValueError(f"Unknown modulation: {mod}")


def _demap_bpsk(symbols: np.ndarray) -> np.ndarray:
    return (symbols.real < 0).astype(np.uint8)


def _demap_qpsk(symbols: np.ndarray, gray_coding: bool) -> np.ndarray:
    # Gray QPSK in iqgen: 00→0°, 01→90°, 11→180°, 10→270°
    idx_gray = _angle_to_index(symbols, 4)
    if gray_coding:
        idx = _gray_to_binary_lut(2)[idx_gray]
    else:
        idx = idx_gray
    return _indices_to_bits(idx, 2)


def _demap_8psk(symbols: np.ndarray, gray_coding: bool) -> np.ndarray:
    idx_gray = _angle_to_index(symbols, 8)
    if gray_coding:
        idx = _gray_to_binary_lut(3)[idx_gray]
    else:
        idx = idx_gray
    return _indices_to_bits(idx, 3)


def _demap_differential(symbols: np.ndarray, base_mod: str,
                         initial_phase: float, gray_coding: bool) -> np.ndarray:
    """Recover the per-symbol phase deltas, then demap as if the deltas
    had been mapped by the base modulation."""
    if symbols.size == 0:
        return np.zeros(0, dtype=np.uint8)
    # Prepend the implicit reference symbol the transmitter used.
    ref = np.exp(1j * initial_phase).astype(np.complex64)
    prev = np.concatenate([[ref], symbols[:-1]])
    deltas = symbols / prev
    # Make magnitudes unit so the demapper sees clean PSK points
    mag = np.abs(deltas)
    mag[mag == 0] = 1.0
    deltas = deltas / mag
    if base_mod == "bpsk":
        return _demap_bpsk(deltas)
    if base_mod == "qpsk":
        return _demap_qpsk(deltas, gray_coding)
    if base_mod == "8psk":
        return _demap_8psk(deltas, gray_coding)
    raise ValueError(f"Unsupported differential base: {base_mod}")


# π/4-DQPSK IS-54 delta-table inverse: Δφ → (b1, b0)
# Forward: 00→+π/4, 01→+3π/4, 10→-π/4, 11→-3π/4
_PI4_DELTA_BITS = {
    0:  (0, 0),  # +π/4
    1:  (0, 1),  # +3π/4
    2:  (1, 1),  # -3π/4 (wraps via angle ordering, see _demap_pi4_qpsk)
    3:  (1, 0),  # -π/4
}


def _demap_pi4_qpsk(symbols: np.ndarray, initial_phase: float) -> np.ndarray:
    if symbols.size == 0:
        return np.zeros(0, dtype=np.uint8)
    ref = np.exp(1j * initial_phase).astype(np.complex64)
    prev = np.concatenate([[ref], symbols[:-1]])
    deltas = symbols / prev
    angles = np.angle(deltas)                          # (-π, π]
    # Round to nearest k·π/4 where k ∈ {-3,-1,+1,+3}
    k = np.round(angles / (np.pi / 4)).astype(np.int64)
    # Map k → (b1, b0) per IS-54 (Gray-coded)
    bits = np.zeros(symbols.size * 2, dtype=np.uint8)
    for i, kk in enumerate(k):
        kk = int(kk)
        if kk == 1:        b1, b0 = 0, 0   # +π/4
        elif kk == 3:      b1, b0 = 0, 1   # +3π/4
        elif kk == -1:     b1, b0 = 1, 0   # -π/4
        elif kk == -3:     b1, b0 = 1, 1   # -3π/4
        else:              b1, b0 = 0, 0   # snap failure (shouldn't happen)
        bits[2 * i]     = b1
        bits[2 * i + 1] = b0
    return bits


# =============================================================================
# Reporting
# =============================================================================

@dataclass
class VerifyReport:
    n_recovered_bits: int
    n_expected_bits: int
    n_compared: int
    n_errors: int

    @property
    def ber(self) -> float:
        return self.n_errors / self.n_compared if self.n_compared else float("nan")

    def __str__(self) -> str:
        if self.n_expected_bits == 0:
            return (f"Recovered {self.n_recovered_bits} bits "
                    f"(no expected bits supplied; no BER computed)")
        return (f"Recovered {self.n_recovered_bits} bits, "
                f"expected {self.n_expected_bits}, "
                f"compared {self.n_compared}, "
                f"errors {self.n_errors}, "
                f"BER {self.ber:.3e}")


def compare_bits(recovered: np.ndarray, expected: np.ndarray) -> VerifyReport:
    n = min(recovered.size, expected.size)
    if n == 0:
        return VerifyReport(recovered.size, expected.size, 0, 0)
    errs = int(np.sum(recovered[:n] != expected[:n]))
    return VerifyReport(recovered.size, expected.size, n, errs)


def parse_bits(s: str) -> np.ndarray:
    """Accept '0'/'1' characters; strip everything else."""
    arr = np.array([int(c) for c in s if c in "01"], dtype=np.uint8)
    return arr


# =============================================================================
# Frame-aware demod
# =============================================================================

def demodulate_frame(iq: np.ndarray, params: "ReceiveParams",
                     frame_config,
                     expected_payload_bits: Optional[np.ndarray] = None,
                     max_sync_distance: Optional[int] = None):
    """Demodulate `iq` and parse the result as a framed packet.

    Returns a tuple `(recovered_bits, FrameReport)`. The raw recovered
    bits are also kept on the report's `payload_bits` (for the payload
    portion) for ease of access.
    """
    from .framing import parse_frame  # local import to keep framing optional
    bits = demodulate(iq, params)
    report = parse_frame(bits, frame_config,
                         expected_payload_bits=expected_payload_bits,
                         max_sync_distance=max_sync_distance)
    return bits, report
